name: "train"

#position in the sky 
ra: 53.11666 
dec: -27.80833

frames:
  - band: "fclear"
    scale: 0.03  # arcsec/pixel, essentially sets the pixel size, for one type of JWST the pixels are 0.03
    noise: 1.0   # set the background image noise to 1.0
    fwhm: 0.09   # PSF FWHM in arcsec (point spread function)
    n_pix_per_side: 224  # number of pixels on a side

sources:
  number: #number of sources in image standard distribution
    mu: 12
    sigma: 7
    min: 0
    max: 49 #1000
  snr: #this is set from the noise image so makes objects of a flux of noise*snr
    powerlaw_index: 1.5
    min: 10.0 
    max: 10000.0
  log_size:  # in arcsec, size of objects in log space
    mu: -1.0
    sigma: 0.4
    min: -1.5
    max: 0.3
  sersic:  # galsim only: n=0.3-6.2, gives the sersic index
    mu: 1.0
    sigma: 1.5
    min: 0.5
    max: 6.0
  q: #this gives the distributions for the view of the galaxies is whether face on (q=1) 
  #or side on q small. q is the ratio of semi major and semi minor axis 
    mu: 0.5
    sigma: 0.25
    min: 0.1
    max: 1.0
